### ISSUE TITLE
marine fishes of St. Eustatius

### ISSUE THREAD

**Issue by wardappeltans** [iobis/dataqueue#4]
will be dealt with by the Caribbean OBIS node

Davies, M.R.; Piontek, S. (2016). The marine fishes of St. Eustatius, Dutch Caribbean. Mar. Biodiv. Online first. hdl.handle.net/10.1007/s12526-016-0575-1

**Comment by ekleins** [comment]
The author was contacted. No resources to provide the detailed table with names/locations. I think he doesn't want to collaborate.
